# Generated by Django 4.1.2 on 2022-10-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_1', models.CharField(max_length=30)),
                ('nombre_2', models.CharField(blank=True, max_length=30, null=True)),
                ('dependencia', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('numero_documento', models.CharField(max_length=30)),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacion', to='main.maestra')),
                ('tipo_sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_sexo', to='main.maestra')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('personaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
                ('tipo_estadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_estadoId', to='main.maestra')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_producto', to='main.maestra')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=30)),
                ('fecha_salida', models.DateField()),
                ('servicioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicio')),
                ('tipo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_estado', to='main.maestra')),
            ],
        ),
    ]
